# Generated by Django 2.2.12 on 2020-08-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(default=0, max_length=600),
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.ManyToManyField(blank=True, to='tgApp.Genre'),
        ),
    ]
