# Generated by Django 2.2.12 on 2020-08-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgApp', '0002_auto_20200819_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subgenre',
            field=models.ManyToManyField(blank=True, default=0, related_name='subjenres', to='tgApp.Subgenre'),
        ),
    ]
